- name: Create temp intall path 
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create a tmp path
      file:
        path: "/tmp/install_gcloud"
        state: directory
        mode: 0777

- name: Run the install
  hosts: localhost
  connection: local
  gather_facts: yes    # Run gather_facts to define ansible_env.HOME
  roles:
    - role: role-install-gcloud
      gcloud_tmp_path: /tmp/install_gcloud 
      gcloud_archive_name: google-cloud-sdk-114.0.0-darwin-x86_64.tar.gz

- name: Remove temp install path
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Remove the tmp path
      file:
        path: "/tmp/install_gcloud"
        state: absent