# Ansible/scale-deployment.yaml
- hosts: localhost
  tasks:
   - name: connecting to cluster
     shell: gcloud container clusters get-credentials {{cluster_name}} --zone {{zone}} --project {{project}}
   - name: scaling the deployment
     shell: helm upgrade {{schoolId}} ./sugarizer-chart --set server.replicas={{scale}},school.Id={{schoolId}}