database:
  image: mikkl/multiarch-mongodb:amd64
  port: 27017

# sugarizer-server settings
server:
  image: llaske/multiarch-node6:amd64
  replicas: 3
  serviceType: LoadBalancer
  httpPortPod: 80
  httpPortExternal: 8080
  presencePort: 8039
  setupCommands: " cd sugarizer-server; git init;
          git remote add origin https://github.com/ksraj123/sugarizer-server.git;
          git fetch origin mongoKubernetes; git pull origin mongoKubernetes; git checkout mongoKubernetes;
          npm install;
          nohup node /sugarizer-server/sugarizer.js /sugarizer-server/env/docker.ini & (sleep 100s && (sh add-admin.sh defaultuser password http://127.0.0.1:80/auth/signup && sleep infinity))"

# sugarizer-client settings
client:
  setupCommands: "cd sugarizer-client; git init;
          git remote add origin https://github.com/llaske/sugarizer;
          git fetch origin master; git pull origin master; cd ..;"