apiVersion: v1
kind: Service
metadata:
  name: {{.Values.school.Id}}-service
  namespace: {{.Values.school.Id}}
spec:
  type: {{ .Values.server.serviceType }}
  ports:
  - port: {{ .Values.server.httpPortExternal }}
    targetPort: {{ .Values.server.httpPortPod }}
    name: http
  - port: {{ .Values.server.presencePort }}
    targetPort: {{ .Values.server.presencePort }}
    name: presence
  selector:
    app: {{ template "sugarizer-chart.fullname" . }}-pod
