apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.school.Id}}
spec:
  capacity:
    storage: 10Gi #capacity of the nfs server
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.{{.Values.school.Id}}.svc.cluster.local
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
  namespace: {{.Values.school.Id}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi #storage claim upto the capacity of the nfs server
